### ISSUE TITLE
How to update xlsx file?

### ISSUE THREAD

**Issue by Cetger** [baranovxyz/xlsx-stream-writer#6]
Hi there, I'm using your library to create a new xlsx file. But I have a problem about it. I have  a standart xlsx file. F.e first 10 rows and sheet name is fix. I want to change only after some rows. I have xlsx file template, i cant break it, i just want to update my data. I hope i could explain what I mean. Is there any way of that take a file, dont change sheet name, first 10 rows, and start to write after 10 rows.
Thanks in advance,

**Comment by cscan** [comment]
Vote this request

**Comment by baranovxyz** [comment]
Hi Cetger,

It is not possible to do this with xlsx-stream-writer. To do this one would need to first read xslx document (which xlsx-stream-writer can not).

xlsx-stream-writer is a library to create xlsx files in streaming mode. It can create very large files up to hundreds of thousands of rows (maybe even millions, depending on data and amount of row).
